server:
  port: 8080

spring:
  application:
    name: SearchIndexer

logging:
  level:
    org.example: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

opensearch:
  uris: http://localhost:9200