[versions]
java = "25"
spring-boot = "4.0.2"
dependency-management = "1.1.6"
junit-bom = "5.10.0"
spring-data-opensearch = "3.0.1"

[libraries]
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }

spring-data-opensearch = { module = "org.opensearch.client:spring-data-opensearch", version.ref = "spring-data-opensearch" }

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit-bom" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

[bundles]
test = ["spring-boot-starter-test", "junit-jupiter", "junit-platform-launcher"]

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
dependency-management = { id = "io.spring.dependency-management", version.ref = "dependency-management" }